
---
apiVersion: v1
kind: Service
metadata:
  name: xxl-executor
spec:
  ports:
  - port: 9999
  selector:
    app: xxl-executor

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl-executor
spec:
  selector:
    matchLabels:
      app: xxl-executor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: xxl-executor
    spec:
      containers:
      - image: taihu/xxlps
        name: xxl-executor
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9999
          name: xxl-executor


          
