apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xxl-job-admin
spec:
  rules:
  - host: "xxl.taihu.org"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: xxl-job-admin
            port:
              number: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: xxl-job-admin
spec:
  ports:
  - port: 8080
  selector:
    app: xxl-job-admin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl-job-admin
spec:
  selector:
    matchLabels:
      app: xxl-job-admin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: xxl-job-admin
    spec:
      containers:
      - image: xuxueli/xxl-job-admin:2.3.0
        name: xxl-job-admin
        env:
        - name: PARAMS
          value: "--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.password=password"
        ports:
        - containerPort: 8080
          name: xxl-job-admin
        volumeMounts:
        - name: xxl-log
          mountPath: /data/applogs
      volumes:
      - name: xxl-log
        persistentVolumeClaim:
          claimName: xxl-log-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xxl-log-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

 


          
