apiVersion: apps/v1
kind: Deployment
metadata:
  name: eagle
spec:
  selector:
    matchLabels:
      app: eagle
  template:
    metadata:
      labels:
        app: eagle
    spec:
      containers:
      - image: xieshujian/eagle:2.0.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8048
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: eagle
        ports:
        - containerPort: 8048
          name: eagle        
        volumeMounts:
        - name: eagle-config
          mountPath: /eagle/conf/system-config.properties
          subPath: system-config.properties
      volumes:
      - name: eagle-config
        configMap:
          name: eagle
          items:
            - key: system-config.properties
              path: system-config.properties
